services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "80:80"
      - "443:443"
    command: python manage.py runserver 0.0.0.0:9000  # Django будет слушать на порту 9000 внутри контейнера
    environment:
      - DJANGO_SETTINGS_MODULE=library.settings

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/app/nginx.conf  # Ваш файл конфигурации Nginx
      - ./static:/app/static  # Пробросим директорию для статики
      - ./media:/app/media  # Пробросим директорию для медиа
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
