services:
  web:
    build: .
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web
    environment:
      - DJANGO_SETTINGS_MODULE=library.settings
    expose:
      - "8000"
    ports:
      - "8000:8000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Ваш файл конфигурации Nginx
      - ./staticfiles:/app/staticfiles  # Пробросим директорию для статики
      - ./media:/app/media  # Пробросим директорию для медиа
      - /etc/letsencrypt:/etc/letsencrypt/live/chorkatedralnysiedlce.pl/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

networks:
  app_network:
    driver: bridge
