services:
  web:
    build: .
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:8001 library.wsgi:application
    container_name: web
    environment:
      - DJANGO_SETTINGS_MODULE=library.settings
    ports:
      - "8000:8001"
    networks:
      - library_app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:./app/nginx.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - /etc/letsencrypt:/etc/letsencrypt/live/chorkatedralnysiedlce.pl/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - library_app_network

networks:
  library_app_network:
    driver: bridge
