services:
  web:
    build: .
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:9000  # Django будет слушать на порту 9000 внутри контейнера
    environment:
      - DJANGO_SETTINGS_MODULE=library.settings
    expose:
      - "9000"
    ports:
      - "9000:9000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/app/nginx.conf  # Ваш файл конфигурации Nginx
      - ./staticfiles:/app/staticfiles  # Пробросим директорию для статики
      - ./media:/app/media  # Пробросим директорию для медиа
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
        - app_network
